# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
  
julia:
  - 1.5

script:
  - julia -e 'using Pkg;  Pkg.add("Test")'
  - julia -e 'using Pkg; Pkg.test(coverage=true)'
